# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/pre-commit/mirrors-yapf
    sha: v0.18.0
    hooks:
    - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    - id: trailing-whitespace
      name: Supprime espaces fin de ligne
      files: .py$
    - id: end-of-file-fixer
      name: Règle problème sur les fins de fichiers
    - id: check-yaml
      name: Syntaxe des fichiers YAML
    - id: check-json
      name: Syntaxe des fichiers JSON
    - id: debug-statements
      name: Supprime les PDB restants
    - id: detect-private-key
      name: Trouve les clefs privées
    - id: flake8
      name: Vérification code Python avec flake8
      args: ["--exclude=.git, __pycache__"]
    - id: requirements-txt-fixer
      name: Réordonne le fichier requirements.txt
#  - repo: https://github.com/pre-commit/mirrors-csslint
#    sha: v1.0.5
#    hooks:
#    - id: csslint
#      name: Vérification CSS
  - repo: https://github.com/pre-commit/mirrors-jshint
    sha: v2.9.5
    hooks:
    - id: jshint
#  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#    sha: v1.0.3
#    hooks:
#      - id: python-bandit-vulnerability-check
#        args: []
#        files: .py$
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    - id: python-safety-dependencies-check
