# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 15:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=254, verbose_name='Ex. FR.CHMF.00.BHZ')),
                ('span',
                 django.contrib.postgres.fields.ranges.DateTimeRangeField(
                     help_text='If no end date for the moment, just add \
start date',
                     verbose_name='Date time range (start/end)')),
            ], ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=254, verbose_name='Serial number')),
            ], ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('chain_type', models.IntegerField(
                    choices=[(0, 'Sensor'), (1, 'Preamplifier'),
                             (2, 'Datalogger'), (3, 'Equipment'),
                             (4, 'Hybrid')])),
            ], ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ], ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('equipment', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='states',
                    to='gissmo.Equipment')),
                ('span',
                 django.contrib.postgres.fields.ranges.DateTimeRangeField(
                     help_text='If no end date for the moment, just add \
start date',
                     verbose_name='Date time range (start/end)')),
            ], ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ], ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('parameter', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='values',
                    to='gissmo.Parameter')),
            ], ),
        migrations.AddField(
            model_name='parameter',
            name='default',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='is_default',
                to='gissmo.Value'), ),
        migrations.AddField(
            model_name='parameter',
            name='model',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='parameters',
                to='gissmo.Model'), ),
        migrations.AddField(
            model_name='model',
            name='_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='models',
                to='gissmo.Type'), ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='equipments',
                to='gissmo.Model'), ),
        migrations.AddField(
            model_name='channel',
            name='states',
            field=models.ManyToManyField(to='gissmo.State'), ),
    ]
