# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 17:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('gissmo', '0002_auto_20180116_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('station', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='notebooks',
                    to='gissmo.Station')),
            ], ),
    ]
